### ISSUE TITLE
generateQrimgcode typo

### ISSUE THREAD

**Issue by linyimin-bupt** [nicejade/arya-jarvis#2]
generateQrimgcode typo cause runtime error:

```
/home/linyimin/projects/arya-jarvis/bin/index.js:148
    generateQrimgcode(string, commands)
    ^

ReferenceError: generateQrimgcode is not defined
    at Command.program.command.description.option.option.action (/home/linyimin/projects/arya-jarvis/bin/index.js:148:5)
    at Command.listener (/home/linyimin/projects/arya-jarvis/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/home/linyimin/projects/arya-jarvis/node_modules/commander/index.js:671:12)
    at Command.parse (/home/linyimin/projects/arya-jarvis/node_modules/commander/index.js:459:21)
    at Object.<anonymous> (/home/linyimin/projects/arya-jarvis/bin/index.js:197:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by nicejade** [comment]
@linyimin-bupt Thank you very much for your feedback and contribution, I will post an update tonight.
